# Generated by Django 3.0.4 on 2022-09-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_person_name_in_dat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_in_dat',
            field=models.CharField(default='_dat', max_length=30, verbose_name='Имя в дательном падеже'),
        ),
    ]
