# Generated by Django 3.0.4 on 2022-09-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_auto_20220921_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_in_dat',
            field=models.CharField(default='dat', max_length=150, verbose_name='Имя в дательном падеже'),
        ),
    ]
