# Generated by Django 3.0.4 on 2022-10-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0002_auto_20221007_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
    ]
