# Generated by Django 3.0.4 on 2022-10-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0003_auto_20221010_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
    ]
