# Generated by Django 3.0.4 on 2022-10-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0004_auto_20221010_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='payment_stauts',
            new_name='payment_status',
        ),
    ]
