# Generated by Django 3.0.4 on 2022-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0005_auto_20221010_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_status',
            field=models.CharField(choices=[('first_pay_wait', 'Платеж 1 ожидание'), ('first_pay_receive', 'Платеж 1 получен'), ('second_pay_wait', 'Платеж 2 ожидание'), ('second_pay_receive', 'Платеж 2 получен'), ('success_fee_wait', 'Финальный платеж ожидание'), ('success_fee_receive', 'Финальный платеж получен'), ('special_terms', 'Особые условия')], default='first_pay', max_length=25, verbose_name='Статус оплаты'),
        ),
    ]
