# Generated by Django 3.0.4 on 2021-09-30 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn_number', models.CharField(max_length=10, unique=True, verbose_name='ИНН')),
                ('ogrn_number', models.CharField(max_length=13, unique=True, verbose_name='ОГРН')),
                ('short_name', models.CharField(max_length=250, verbose_name='Сокращенное наименование')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное наименование')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=124, null=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Короткое название проекта')),
                ('full_name', models.CharField(blank=True, max_length=500, unique=True, verbose_name='Полное название проекта')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('start_date', models.DateField(null=True, verbose_name='Начало проекта')),
                ('end_date', models.DateField(null=True, verbose_name='Окончание проекта')),
                ('grant', models.FloatField(null=True, verbose_name='Грант')),
                ('full_cost', models.FloatField(null=True, verbose_name='Бюджет проекта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.Company', verbose_name='Компания')),
                ('contacts', models.ManyToManyField(related_name='projects', to='crm.Contact', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый проект'), ('progress', 'В работе'), ('finished', 'Работа завершена')], max_length=10, verbose_name='Статус')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='crm.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Статус проекта',
                'verbose_name_plural': 'Статусы проектов',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consult', 'Консультация'), ('discuss', 'Обсуждение'), ('call', 'Созвон'), ('due_dil', 'Контрактация'), ('formal', 'Формальная проверка')], max_length=7, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('small', models.BooleanField(default=True, verbose_name='Локальное событие')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Автор события')),
                ('invited_persons', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Приглашенные сотрудники')),
                ('projects', models.ManyToManyField(related_name='events', to='crm.Project', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='companies', to='crm.Contact', verbose_name='Контакты'),
        ),
    ]
