# Generated by Django 3.0.4 on 2021-10-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('conditions_of_work', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_deliver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.ProjectDeliver', verbose_name='Источник проекта'),
        ),
    ]
