# Generated by Django 3.0.4 on 2021-10-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20211016_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdeliver',
            options={'verbose_name': 'Источник проекта', 'verbose_name_plural': 'Источники проекта'},
        ),
    ]
