# Generated by Django 3.0.4 on 2021-10-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20211017_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeliver',
            name='slug',
            field=models.SlugField(default='test', max_length=55),
            preserve_default=False,
        ),
    ]
