# Generated by Django 3.0.4 on 2021-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_projectdeliver_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeliver',
            name='slug',
            field=models.SlugField(default='user', max_length=55),
        ),
    ]
