# Generated by Django 3.0.4 on 2021-12-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20211030_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('consult', 'Консультация'), ('discuss', 'Обсуждение'), ('call', 'Созвон'), ('due_dil', 'Контрактация'), ('paper_check', 'Работа с документами')], max_length=25, verbose_name='Категория'),
        ),
    ]
