# Generated by Django 3.0.4 on 2021-12-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20211228_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('text_consult', 'Письменная консультация'), ('phone_consult', 'Телефонная консультация'), ('call', 'ВКС'), ('document_transfer', 'Обмен документами'), ('paper_check', 'Работа с документами'), ('data_request', 'Запрос информации'), ('project_update', 'Изменение статуса'), ('discuss', 'Обсуждение'), ('due_dil', 'Контрактация')], max_length=25, verbose_name='Категория'),
        ),
    ]
