# Generated by Django 3.0.4 on 2022-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20211228_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='project_type',
        ),
        migrations.AlterField(
            model_name='project',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='projects', to='crm.Contact', verbose_name='Контакты'),
        ),
    ]
