# Generated by Django 3.0.4 on 2022-05-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20220508_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='project_type',
            new_name='event_type',
        ),
    ]
