# Generated by Django 3.0.4 on 2022-05-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20220508_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='category',
        ),
    ]
