# Generated by Django 3.0.4 on 2022-05-22 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0017_auto_20220514_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='small',
            field=models.BooleanField(default=False, verbose_name='Добавить в календарь'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название задачи')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('doers', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители')),
                ('events', models.ManyToManyField(related_name='tasks', to='crm.Event', verbose_name='События')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
