# Generated by Django 3.0.4 on 2022-05-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20220522_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='doers',
            new_name='doer',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='events',
            new_name='event',
        ),
    ]
