# Generated by Django 3.0.4 on 2022-05-24 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20220524_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 24, 5, 22, 57, 857129, tzinfo=utc), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 5, 24, 5, 22, 57, 857173, tzinfo=utc), null=True, verbose_name='Время'),
        ),
    ]
