# Generated by Django 3.0.4 on 2022-05-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20220524_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Задача'),
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kick_off_meeting', models.BooleanField(default=False, verbose_name='Установочная встреча')),
                ('contract', models.BooleanField(default=False, verbose_name='Договор')),
                ('to_do_list', models.BooleanField(default=False, verbose_name='To-Do List')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roadmap', to='crm.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Дорожная карта',
                'verbose_name_plural': 'Дорожные карты',
            },
        ),
    ]
