# Generated by Django 3.0.4 on 2022-06-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20220526_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='application',
            field=models.BooleanField(default=False, verbose_name='Заявка подана'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='first_pay',
            field=models.BooleanField(default=False, verbose_name='Аванс получен'),
        ),
    ]
