# Generated by Django 3.0.4 on 2022-06-03 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0026_auto_20220602_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='changer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_satatus_changes', to=settings.AUTH_USER_MODEL, verbose_name='Автор статуса'),
        ),
    ]
