# Generated by Django 3.0.4 on 2022-06-03 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_taskstatus_changer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Дата'),
        ),
    ]
