# Generated by Django 3.0.4 on 2022-06-03 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20220603_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Время'),
        ),
    ]
