# Generated by Django 3.0.4 on 2022-06-03 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20220603_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='date',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='Дата'),
        ),
    ]
