# Generated by Django 3.0.4 on 2022-06-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20220603_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gc_calenar_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
