# Generated by Django 3.0.4 on 2022-06-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_event_gc_calenar_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='gc_calenar_id',
            new_name='gc_event_id',
        ),
    ]
