# Generated by Django 3.0.4 on 2022-06-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20220619_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткий статус'),
        ),
    ]
