# Generated by Django 3.0.4 on 2022-06-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_project_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Телефон'),
        ),
    ]
