# Generated by Django 3.0.4 on 2022-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20220930_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Тег'),
        ),
    ]
